export namespace TYPE_NAMES {
    let OBJECT_ACCESS_METHOD: string;
    let OBJECT_AGGREGATE: string;
    let OBJECT_ATTRIBUTE: string;
    let OBJECT_CAST: string;
    let OBJECT_COLLATION: string;
    let OBJECT_COLUMN: string;
    let OBJECT_CONVERSION: string;
    let OBJECT_DATABASE: string;
    let OBJECT_DOMAIN: string;
    let OBJECT_DOMCONSTRAINT: string;
    let OBJECT_EVENT_TRIGGER: string;
    let OBJECT_EXTENSION: string;
    let OBJECT_FDW: string;
    let OBJECT_FOREIGN_SERVER: string;
    let OBJECT_FOREIGN_TABLE: string;
    let OBJECT_FUNCTION: string;
    let OBJECT_INDEX: string;
    let OBJECT_LANGUAGE: string;
    let OBJECT_LARGEOBJECT: string;
    let OBJECT_MATVIEW: string;
    let OBJECT_OPCLASS: string;
    let OBJECT_OPERATOR: string;
    let OBJECT_OPFAMILY: string;
    let OBJECT_POLICY: string;
    let OBJECT_PROCEDURE: string;
    let OBJECT_PUBLICATION: string;
    let OBJECT_ROLE: string;
    let OBJECT_ROUTINE: string;
    let OBJECT_RULE: string;
    let OBJECT_SCHEMA: string;
    let OBJECT_SEQUENCE: string;
    let OBJECT_STATISTIC_EXT: string;
    let OBJECT_SUBSCRIPTION: string;
    let OBJECT_TABCONSTRAINT: string;
    let OBJECT_TABLE: string;
    let OBJECT_TABLESPACE: string;
    let OBJECT_TRANSFORM: string;
    let OBJECT_TRIGGER: string;
    let OBJECT_TSCONFIGURATION: string;
    let OBJECT_TSDICTIONARY: string;
    let OBJECT_TSPARSER: string;
    let OBJECT_TSTEMPLATE: string;
    let OBJECT_TYPE: string;
    let OBJECT_VIEW: string;
}
export function objtypeName(arg: any): any;
export function getConstraintFromConstrType(type: any): "NULL" | "NOT NULL" | "DEFAULT" | "CHECK" | "PRIMARY KEY" | "UNIQUE" | "EXCLUDE" | "REFERENCES" | "GENERATED" | "IDENTITY";
