export declare const TYPE_NAMES: {
    OBJECT_ACCESS_METHOD: string;
    OBJECT_AGGREGATE: string;
    OBJECT_ATTRIBUTE: string;
    OBJECT_CAST: string;
    OBJECT_COLLATION: string;
    OBJECT_COLUMN: string;
    OBJECT_CONVERSION: string;
    OBJECT_DATABASE: string;
    OBJECT_DOMAIN: string;
    OBJECT_DOMCONSTRAINT: string;
    OBJECT_EVENT_TRIGGER: string;
    OBJECT_EXTENSION: string;
    OBJECT_FDW: string;
    OBJECT_FOREIGN_SERVER: string;
    OBJECT_FOREIGN_TABLE: string;
    OBJECT_FUNCTION: string;
    OBJECT_INDEX: string;
    OBJECT_LANGUAGE: string;
    OBJECT_LARGEOBJECT: string;
    OBJECT_MATVIEW: string;
    OBJECT_OPCLASS: string;
    OBJECT_OPERATOR: string;
    OBJECT_OPFAMILY: string;
    OBJECT_POLICY: string;
    OBJECT_PROCEDURE: string;
    OBJECT_PUBLICATION: string;
    OBJECT_ROLE: string;
    OBJECT_ROUTINE: string;
    OBJECT_RULE: string;
    OBJECT_SCHEMA: string;
    OBJECT_SEQUENCE: string;
    OBJECT_STATISTIC_EXT: string;
    OBJECT_SUBSCRIPTION: string;
    OBJECT_TABCONSTRAINT: string;
    OBJECT_TABLE: string;
    OBJECT_TABLESPACE: string;
    OBJECT_TRANSFORM: string;
    OBJECT_TRIGGER: string;
    OBJECT_TSCONFIGURATION: string;
    OBJECT_TSDICTIONARY: string;
    OBJECT_TSPARSER: string;
    OBJECT_TSTEMPLATE: string;
    OBJECT_TYPE: string;
    OBJECT_VIEW: string;
};
export declare const objtypeName: (arg: any) => any;
export declare const getConstraintFromConstrType: (type: any) => "NULL" | "NOT NULL" | "DEFAULT" | "CHECK" | "PRIMARY KEY" | "UNIQUE" | "EXCLUDE" | "REFERENCES" | "GENERATED" | "IDENTITY";
