#!/usr/bin/env node

require('babel-core/register')();

const parser = require('./src');

function runQuery(content) {
  const result = parser.Deparser.deparse(parser.parse(content).query);
  console.log(result);
}

if (process.argv[2]) {
  runQuery(process.argv[2]);
} else {
  let content = '';

  process.stdin.resume();

  process.stdin.on('data', (buf) => {
    content += buf.toString();
  });

  process.stdin.on('end', () => {
    runQuery(content);
  });
}

