#!/usr/bin/env node

const parser = require('pg-query-native');

function runQuery(query) {
  const result = parser.parse(query).query;
  console.log(JSON.stringify(result, null, '  '));
}

if (process.argv[2]) {
  runQuery(process.argv[2]);
} else {
  var content = '';

  process.stdin.resume();

  process.stdin.on('data', (buf) => {
    content += buf.toString();
  });

  process.stdin.on('end', () => {
    runQuery(content);
  });
}

