#!/usr/bin/env node

require('coffee-script/register');
require('babel-core/register')();

const parser = require('./src');

const exec = require('child_process').exec;
const fs = require('fs');

function runQuery(content) {
  const result = parser.deparse(parser.parse(content).query);

  const json1 = parser.clean(parser.parse(content).query);
  const json2 = parser.clean(parser.parse(result).query);

  const same = parser.verify(content);

  if (same) {
    console.log('OK');
  } else {
    console.log('NOT OK');

    fs.writeFileSync('a.json', JSON.stringify(json1, null, '  '));
    fs.writeFileSync('b.json', JSON.stringify(json2, null, '  '));

    exec('diff -C10 a.json b.json', (error, stdout, stderr) => {
      if (error) {
        console.log(error);
      }
      console.log(stdout);
    });
  }
}

if (process.argv[2]) {
  runQuery(process.argv[2]);
} else {
  var content = '';

  process.stdin.resume();

  process.stdin.on('data', (buf) => {
    content += buf.toString();
  });

  process.stdin.on('end', () => {
    runQuery(content);
  });
}
