CREATE TABLE people(
    color_id int GENERATED ALWAYS AS IDENTITY (START WITH 17 INCREMENT BY 21),
    height_cm numeric,
    height_in numeric GENERATED ALWAYS AS (height_cm / 2.54) STORED,
    gen_def_identity numeric GENERATED BY DEFAULT AS IDENTITY,
    gen_alw_identity numeric GENERATED ALWAYS AS IDENTITY
);