export type SkipTest = [
    versionPrevious: number,
    versionNext: number,
    test: string,
    reason: string
];

export const transformerErrors: SkipTest[] = [
    [16, 17, "pretty/misc-5.sql", "16-17 transformer fails WITH clause TypeCast prefix issue: transformer adds pg_catalog prefix to JSON types when expected output has none"],
    [16, 17, "misc/quotes_etc-26.sql", "16-17 Parser-level \v character escape sequence difference: PG16 parser outputs 'v' but PG17 parser outputs '\u000b' (vertical tab)"],
    [16, 17, "latest/postgres/create_am-96.sql", "16-17 transformer fails with 'syntax error at or near 'DEFAULT'"],
    [16, 17, "latest/postgres/create_am-74.sql", "16-17 transformer fails with 'syntax error at or near 'DEFAULT'"],
    [16, 17, "latest/postgres/create_am-65.sql", "16-17 transformer fails with 'syntax error at or near 'DEFAULT'"],
    [16, 17, "latest/postgres/create_am-109.sql", "16-17 transformer fails with 'syntax error at or near 'DEFAULT'"],
    [16, 17, "latest/postgres/create_am-106.sql", "16-17 transformer fails with 'syntax error at or near 'DEFAULT'"],

    [15, 16, "original/upstream/json-102.sql", "15-16 transformer fails with function name transformation - adds pg_catalog schema qualification"],
    [15, 16, "latest/postgres/create_view-281.sql", "15-16 transformer fails with AST transformation mismatch"],
    // [15, 16, "latest/postgres/create_index-85.sql", "15-16 transformer fails with missing nulls_not_distinct property"],
    // [15, 16, "latest/postgres/create_index-83.sql", "15-16 transformer fails with missing nulls_not_distinct property"],
    // [15, 16, "latest/postgres/create_index-72.sql", "15-16 transformer fails with missing nulls_not_distinct property"],
    [15, 16, "latest/postgres/create_index-326.sql", "15-16 transformer fails with syntax error at end of input"],
    // [15, 16, "latest/postgres/create_index-184.sql", "15-16 transformer fails with missing nulls_not_distinct property"],

    [14, 15, "latest/postgres/create_index-345.sql", "AST transformation mismatch (extra \"num\": 1 field)"],

    [13, 14, "original/upstream/rangetypes-300.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN for function parameters"],
    [13, 14, "original/upstream/rangetypes-294.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN for function parameters"],
    [13, 14, "original/upstream/rangetypes-281.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN for function parameters"],
    [13, 14, "original/upstream/rangefuncs-295.sql", "AST transformer bug - removes parameter names from function parameters in DROP FUNCTION statements"],
    [13, 14, "original/upstream/rangefuncs-290.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN in CREATE FUNCTION statements"],
    [13, 14, "original/upstream/rangefuncs-257.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN in CREATE FUNCTION statements"],
    [13, 14, "original/upstream/rangefuncs-247.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN in CREATE FUNCTION statements"],
    [13, 14, "original/upstream/rangefuncs-246.sql", "AST transformer bug - converts FUNC_PARAM_IN/FUNC_PARAM_INOUT to FUNC_PARAM_DEFAULT and removes parameter names"],
    [13, 14, "original/upstream/rangefuncs-245.sql", "AST transformer bug - incorrectly handles function parameters in DROP FUNCTION statements, removes parameters and changes modes"],
    [13, 14, "original/upstream/polymorphism-243.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN in CREATE FUNCTION statements with default parameter values"],
    [13, 14, "original/upstream/polymorphism-242.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN in CREATE FUNCTION statements with default parameter values"],
    [13, 14, "original/upstream/polymorphism-237.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN in CREATE FUNCTION statements with default parameter values"],
    [13, 14, "original/upstream/polymorphism-236.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN in CREATE FUNCTION statements with default parameter values"],
    [13, 14, "original/upstream/polymorphism-227.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN in CREATE FUNCTION statements with default parameter values"],
    [13, 14, "original/upstream/polymorphism-195.sql", "AST transformer bug - converts FUNC_PARAM_VARIADIC to FUNC_PARAM_DEFAULT and removes parameter names in DROP FUNCTION statements with variadic parameters"],
    [13, 14, "original/upstream/polymorphism-157.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN in CREATE FUNCTION statements with default parameter values"],
    [13, 14, "original/upstream/plpgsql-828.sql", "AST transformer bug - incorrectly removes parameter names from objfuncargs in DROP FUNCTION statements with multiple parameters"],
    [13, 14, "original/upstream/plpgsql-732.sql", "AST transformer bug - incorrectly removes parameter names from objfuncargs in DROP FUNCTION statements"],
    [13, 14, "original/upstream/plpgsql-709.sql", "AST transformer bug - converts FUNC_PARAM_IN to FUNC_PARAM_DEFAULT in CREATE FUNCTION statements with default parameter values"],
    [13, 14, "original/upstream/groupingsets-6.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN in CREATE FUNCTION statements with default parameter values"],
    [13, 14, "original/upstream/create_function_3-52.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN in CREATE FUNCTION statements with default parameter values"],
    [13, 14, "original/upstream/create_function_3-51.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN in CREATE FUNCTION statements with default parameter values"],
    [13, 14, "latest/postgres/create_procedure-84.sql", "AST transformer bug - incorrectly converts objname structure from array to object with numbered keys in ALTER PROCEDURE statements"],
    [13, 14, "latest/postgres/create_procedure-80.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN in CREATE PROCEDURE statements with default parameter values"],
    [13, 14, "latest/postgres/create_procedure-72.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN in CREATE PROCEDURE statements with default parameter values"],
    [13, 14, "latest/postgres/create_procedure-68.sql", "AST transformer bug - incorrectly handles function parameters in DROP PROCEDURE statements, adds extra parameters and changes modes"],
    [13, 14, "latest/postgres/create_procedure-64.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN in CREATE PROCEDURE statements with default parameter values"],
    [13, 14, "latest/postgres/create_procedure-41.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN in CREATE PROCEDURE statements with default parameter values"],
    [13, 14, "latest/postgres/create_procedure-102.sql", "AST transformer bug - incorrectly removes objfuncargs array from DROP ROUTINE statements"],
    [13, 14, "latest/postgres/create_index-403.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-378.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-373.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-372.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-368.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-366.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-365.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-351.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-338.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-337.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-334.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-327.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-324.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-323.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-322.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-321.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-320.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-318.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-311.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-302.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-300.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-296.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-285.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-283.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-279.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-278.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-276.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-275.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-256.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-250.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-243.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-237.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-229.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-228.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-227.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-223.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_index-222.sql", "AST transformer bug - missing params array with concurrently DefElem in ReindexStmt"],
    [13, 14, "latest/postgres/create_function_sql-91.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN in CREATE FUNCTION statements with default parameter values"],
    [13, 14, "latest/postgres/create_function_sql-90.sql", "AST transformer bug - converts FUNC_PARAM_DEFAULT to FUNC_PARAM_IN in CREATE FUNCTION statements with default parameter values"],
    [13, 14, "latest/postgres/create_function_sql-115.sql", "AST transformer bug - incorrectly adds parameter names to objfuncargs in DROP FUNCTION statements"],
];  