CREATE ROLE app_anonymous;
CREATE ROLE app_authenticated;
CREATE ROLE app_user LOGIN PASSWORD 'xyz';

CREATE ROLE miriam WITH LOGIN PASSWORD 'jw8s0F4' VALID UNTIL '2005-01-01';

CREATE ROLE admin1 WITH LOGIN PASSWORD 'jw8s0F4' CREATEDB CREATEROLE INHERIT;

CREATE ROLE admin2 WITH NOLOGIN NOCREATEDB NOCREATEROLE;

CREATE ROLE authy WITH ADMIN app_authenticated;
