
import { FixtureTestUtils } from '../../test-utils';
const fixtures = new FixtureTestUtils();

it('latest-postgres-random', () => {
  fixtures.runFixtureTests([
  "random-1.sql",
  "random-2.sql",
  "random-3.sql",
  "random-4.sql",
  "random-5.sql",
  "random-6.sql",
  "random-7.sql",
  "random-8.sql",
  "random-9.sql",
  "random-10.sql",
  "random-11.sql",
  "random-12.sql",
  "random-13.sql",
  "random-14.sql",
  "random-15.sql",
  "random-16.sql",
  "random-17.sql",
  "random-18.sql",
  "random-19.sql",
  "random-20.sql",
  "random-21.sql",
  "random-22.sql",
  "random-23.sql",
  "random-24.sql",
  "random-25.sql",
  "random-26.sql",
  "random-27.sql",
  "random-28.sql",
  "random-29.sql",
  "random-30.sql",
  "random-31.sql",
  "random-32.sql",
  "random-33.sql",
  "random-34.sql",
  "random-35.sql",
  "random-36.sql",
  "random-37.sql",
  "random-38.sql",
  "random-39.sql",
  "random-40.sql",
  "random-41.sql",
  "random-42.sql",
  "random-43.sql",
  "random-44.sql",
  "random-45.sql",
  "random-46.sql",
  "random-47.sql",
  "random-48.sql"
]);
});
