
import { FixtureTestUtils } from '../../test-utils';
const fixtures = new FixtureTestUtils();

it('latest-postgres-tidscan', () => {
  fixtures.runFixtureTests([
  "tidscan-1.sql",
  "tidscan-2.sql",
  "tidscan-3.sql",
  "tidscan-4.sql",
  "tidscan-5.sql",
  "tidscan-6.sql",
  "tidscan-7.sql",
  "tidscan-8.sql",
  "tidscan-9.sql",
  "tidscan-10.sql",
  "tidscan-11.sql",
  "tidscan-12.sql",
  "tidscan-13.sql",
  "tidscan-14.sql",
  "tidscan-15.sql",
  "tidscan-16.sql",
  "tidscan-17.sql",
  "tidscan-18.sql",
  "tidscan-19.sql",
  "tidscan-20.sql",
  "tidscan-21.sql",
  "tidscan-22.sql",
  "tidscan-23.sql",
  "tidscan-24.sql",
  "tidscan-25.sql",
  "tidscan-26.sql",
  "tidscan-27.sql",
  "tidscan-28.sql",
  "tidscan-29.sql",
  "tidscan-30.sql",
  "tidscan-31.sql",
  "tidscan-32.sql",
  "tidscan-33.sql",
  "tidscan-34.sql",
  "tidscan-35.sql",
  "tidscan-36.sql",
  "tidscan-37.sql",
  "tidscan-38.sql",
  "tidscan-39.sql",
  "tidscan-40.sql",
  "tidscan-41.sql",
  "tidscan-42.sql",
  "tidscan-43.sql",
  "tidscan-44.sql",
  "tidscan-45.sql",
  "tidscan-46.sql",
  "tidscan-47.sql",
  "tidscan-48.sql",
  "tidscan-49.sql"
]);
});
