
import { FixtureTestUtils } from '../../test-utils';
const fixtures = new FixtureTestUtils();

it('line', () => {
  fixtures.runFixtureTests([
  "line-1.sql",
  "line-2.sql",
  "line-3.sql",
  "line-4.sql",
  "line-5.sql",
  "line-6.sql",
  "line-7.sql",
  "line-8.sql",
  "line-9.sql",
  "line-10.sql",
  "line-11.sql",
  "line-12.sql",
  "line-13.sql",
  "line-14.sql",
  "line-15.sql",
  "line-16.sql",
  "line-17.sql",
  "line-18.sql",
  "line-19.sql",
  "line-20.sql",
  "line-21.sql",
  "line-22.sql",
  "line-23.sql",
  "line-24.sql",
  "line-25.sql",
  "line-26.sql",
  "line-27.sql",
  "line-28.sql",
  "line-29.sql",
  "line-30.sql",
  "line-31.sql",
  "line-32.sql",
  "line-33.sql",
  "line-34.sql",
  "line-35.sql",
  "line-36.sql",
  "line-37.sql",
  "line-38.sql",
  "line-39.sql",
  "line-40.sql",
  "line-41.sql",
  "line-42.sql",
  "line-43.sql",
  "line-44.sql",
  "line-45.sql",
  "line-46.sql",
  "line-47.sql",
  "line-48.sql",
  "line-49.sql",
  "line-50.sql"
]);
});
