
import { FixtureTestUtils } from '../../test-utils';
const fixtures = new FixtureTestUtils();

it('original-upstream-int2', () => {
  fixtures.runFixtureTests([
  "original/upstream/int2-1.sql",
  "original/upstream/int2-2.sql",
  "original/upstream/int2-3.sql",
  "original/upstream/int2-4.sql",
  "original/upstream/int2-5.sql",
  "original/upstream/int2-6.sql",
  "original/upstream/int2-7.sql",
  "original/upstream/int2-8.sql",
  "original/upstream/int2-9.sql",
  "original/upstream/int2-10.sql",
  "original/upstream/int2-11.sql",
  "original/upstream/int2-12.sql",
  "original/upstream/int2-13.sql",
  "original/upstream/int2-14.sql",
  "original/upstream/int2-15.sql",
  "original/upstream/int2-16.sql",
  "original/upstream/int2-17.sql",
  "original/upstream/int2-18.sql",
  "original/upstream/int2-19.sql",
  "original/upstream/int2-20.sql",
  "original/upstream/int2-21.sql",
  "original/upstream/int2-22.sql",
  "original/upstream/int2-23.sql",
  "original/upstream/int2-24.sql",
  "original/upstream/int2-25.sql",
  "original/upstream/int2-26.sql",
  "original/upstream/int2-27.sql",
  "original/upstream/int2-28.sql",
  "original/upstream/int2-29.sql",
  "original/upstream/int2-30.sql",
  "original/upstream/int2-31.sql",
  "original/upstream/int2-32.sql",
  "original/upstream/int2-33.sql",
  "original/upstream/int2-34.sql",
  "original/upstream/int2-35.sql",
  "original/upstream/int2-36.sql",
  "original/upstream/int2-37.sql",
  "original/upstream/int2-38.sql",
  "original/upstream/int2-39.sql",
  "original/upstream/int2-40.sql",
  "original/upstream/int2-41.sql",
  "original/upstream/int2-42.sql",
  "original/upstream/int2-43.sql",
  "original/upstream/int2-44.sql",
  "original/upstream/int2-45.sql",
  "original/upstream/int2-46.sql",
  "original/upstream/int2-47.sql"
]);
});
