
import { FixtureTestUtils } from '../../test-utils';
const fixtures = new FixtureTestUtils();

it('original-upstream-tablesample', () => {
  fixtures.runFixtureTests([
  "original/upstream/tablesample-1.sql",
  "original/upstream/tablesample-2.sql",
  "original/upstream/tablesample-3.sql",
  "original/upstream/tablesample-4.sql",
  "original/upstream/tablesample-5.sql",
  "original/upstream/tablesample-6.sql",
  "original/upstream/tablesample-7.sql",
  "original/upstream/tablesample-8.sql",
  "original/upstream/tablesample-9.sql",
  "original/upstream/tablesample-10.sql",
  "original/upstream/tablesample-11.sql",
  "original/upstream/tablesample-12.sql",
  "original/upstream/tablesample-13.sql",
  "original/upstream/tablesample-14.sql",
  "original/upstream/tablesample-15.sql",
  "original/upstream/tablesample-16.sql",
  "original/upstream/tablesample-17.sql",
  "original/upstream/tablesample-18.sql",
  "original/upstream/tablesample-19.sql",
  "original/upstream/tablesample-20.sql",
  "original/upstream/tablesample-21.sql",
  "original/upstream/tablesample-22.sql",
  "original/upstream/tablesample-23.sql",
  "original/upstream/tablesample-24.sql",
  "original/upstream/tablesample-25.sql",
  "original/upstream/tablesample-26.sql",
  "original/upstream/tablesample-27.sql",
  "original/upstream/tablesample-28.sql",
  "original/upstream/tablesample-29.sql",
  "original/upstream/tablesample-30.sql",
  "original/upstream/tablesample-31.sql",
  "original/upstream/tablesample-32.sql",
  "original/upstream/tablesample-33.sql",
  "original/upstream/tablesample-34.sql",
  "original/upstream/tablesample-35.sql",
  "original/upstream/tablesample-36.sql",
  "original/upstream/tablesample-37.sql",
  "original/upstream/tablesample-38.sql",
  "original/upstream/tablesample-39.sql",
  "original/upstream/tablesample-40.sql",
  "original/upstream/tablesample-41.sql",
  "original/upstream/tablesample-42.sql",
  "original/upstream/tablesample-43.sql",
  "original/upstream/tablesample-44.sql",
  "original/upstream/tablesample-45.sql",
  "original/upstream/tablesample-46.sql",
  "original/upstream/tablesample-47.sql",
  "original/upstream/tablesample-48.sql",
  "original/upstream/tablesample-49.sql"
]);
});
