
import { FixtureTestUtils } from '../../test-utils';
const fixtures = new FixtureTestUtils();

it('original-upstream-lock', () => {
  fixtures.runFixtureTests([
  "original/upstream/lock-1.sql",
  "original/upstream/lock-2.sql",
  "original/upstream/lock-3.sql",
  "original/upstream/lock-4.sql",
  "original/upstream/lock-5.sql",
  "original/upstream/lock-6.sql",
  "original/upstream/lock-7.sql",
  "original/upstream/lock-8.sql",
  "original/upstream/lock-9.sql",
  "original/upstream/lock-10.sql",
  "original/upstream/lock-11.sql",
  "original/upstream/lock-12.sql",
  "original/upstream/lock-13.sql",
  "original/upstream/lock-14.sql",
  "original/upstream/lock-15.sql",
  "original/upstream/lock-16.sql",
  "original/upstream/lock-17.sql",
  "original/upstream/lock-18.sql",
  "original/upstream/lock-19.sql",
  "original/upstream/lock-20.sql",
  "original/upstream/lock-21.sql",
  "original/upstream/lock-22.sql",
  "original/upstream/lock-23.sql",
  "original/upstream/lock-24.sql",
  "original/upstream/lock-25.sql",
  "original/upstream/lock-26.sql",
  "original/upstream/lock-27.sql",
  "original/upstream/lock-28.sql",
  "original/upstream/lock-29.sql",
  "original/upstream/lock-30.sql",
  "original/upstream/lock-31.sql",
  "original/upstream/lock-32.sql",
  "original/upstream/lock-33.sql",
  "original/upstream/lock-34.sql",
  "original/upstream/lock-35.sql",
  "original/upstream/lock-36.sql",
  "original/upstream/lock-37.sql",
  "original/upstream/lock-38.sql",
  "original/upstream/lock-39.sql",
  "original/upstream/lock-40.sql",
  "original/upstream/lock-41.sql",
  "original/upstream/lock-42.sql",
  "original/upstream/lock-43.sql",
  "original/upstream/lock-44.sql",
  "original/upstream/lock-45.sql",
  "original/upstream/lock-46.sql",
  "original/upstream/lock-47.sql",
  "original/upstream/lock-48.sql",
  "original/upstream/lock-49.sql",
  "original/upstream/lock-50.sql"
]);
});
