
import { FixtureTestUtils } from '../../test-utils';
const fixtures = new FixtureTestUtils();

it('original-upstream-float4', () => {
  fixtures.runFixtureTests([
  "original/upstream/float4-1.sql",
  "original/upstream/float4-2.sql",
  "original/upstream/float4-3.sql",
  "original/upstream/float4-4.sql",
  "original/upstream/float4-5.sql",
  "original/upstream/float4-6.sql",
  "original/upstream/float4-7.sql",
  "original/upstream/float4-8.sql",
  "original/upstream/float4-9.sql",
  "original/upstream/float4-10.sql",
  "original/upstream/float4-11.sql",
  "original/upstream/float4-12.sql",
  "original/upstream/float4-13.sql",
  "original/upstream/float4-14.sql",
  "original/upstream/float4-15.sql",
  "original/upstream/float4-16.sql",
  "original/upstream/float4-17.sql",
  "original/upstream/float4-18.sql",
  "original/upstream/float4-19.sql",
  "original/upstream/float4-20.sql",
  "original/upstream/float4-21.sql",
  "original/upstream/float4-22.sql",
  "original/upstream/float4-23.sql",
  "original/upstream/float4-24.sql",
  "original/upstream/float4-25.sql",
  "original/upstream/float4-26.sql",
  "original/upstream/float4-27.sql",
  "original/upstream/float4-28.sql",
  "original/upstream/float4-29.sql",
  "original/upstream/float4-30.sql",
  "original/upstream/float4-31.sql",
  "original/upstream/float4-32.sql",
  "original/upstream/float4-33.sql",
  "original/upstream/float4-34.sql",
  "original/upstream/float4-35.sql",
  "original/upstream/float4-36.sql",
  "original/upstream/float4-37.sql",
  "original/upstream/float4-38.sql",
  "original/upstream/float4-39.sql",
  "original/upstream/float4-40.sql",
  "original/upstream/float4-41.sql",
  "original/upstream/float4-42.sql",
  "original/upstream/float4-43.sql",
  "original/upstream/float4-44.sql",
  "original/upstream/float4-45.sql",
  "original/upstream/float4-46.sql"
]);
});
