
import { FixtureTestUtils } from '../../test-utils';
const fixtures = new FixtureTestUtils();

it('original-upstream-line', () => {
  fixtures.runFixtureTests([
  "original/upstream/line-1.sql",
  "original/upstream/line-2.sql",
  "original/upstream/line-3.sql",
  "original/upstream/line-4.sql",
  "original/upstream/line-5.sql",
  "original/upstream/line-6.sql",
  "original/upstream/line-7.sql",
  "original/upstream/line-8.sql",
  "original/upstream/line-9.sql",
  "original/upstream/line-10.sql",
  "original/upstream/line-11.sql",
  "original/upstream/line-12.sql",
  "original/upstream/line-13.sql",
  "original/upstream/line-14.sql",
  "original/upstream/line-15.sql",
  "original/upstream/line-16.sql",
  "original/upstream/line-17.sql",
  "original/upstream/line-18.sql",
  "original/upstream/line-19.sql",
  "original/upstream/line-20.sql",
  "original/upstream/line-21.sql",
  "original/upstream/line-22.sql",
  "original/upstream/line-23.sql",
  "original/upstream/line-24.sql",
  "original/upstream/line-25.sql",
  "original/upstream/line-26.sql",
  "original/upstream/line-27.sql",
  "original/upstream/line-28.sql",
  "original/upstream/line-29.sql",
  "original/upstream/line-30.sql",
  "original/upstream/line-31.sql",
  "original/upstream/line-32.sql",
  "original/upstream/line-33.sql",
  "original/upstream/line-34.sql",
  "original/upstream/line-35.sql",
  "original/upstream/line-36.sql",
  "original/upstream/line-37.sql",
  "original/upstream/line-38.sql",
  "original/upstream/line-39.sql",
  "original/upstream/line-40.sql",
  "original/upstream/line-41.sql",
  "original/upstream/line-42.sql",
  "original/upstream/line-43.sql",
  "original/upstream/line-44.sql",
  "original/upstream/line-45.sql",
  "original/upstream/line-46.sql",
  "original/upstream/line-47.sql",
  "original/upstream/line-48.sql",
  "original/upstream/line-49.sql",
  "original/upstream/line-50.sql"
]);
});
