
import { FixtureTestUtils } from '../../test-utils';
const fixtures = new FixtureTestUtils();

it('tablesample', () => {
  fixtures.runFixtureTests([
  "tablesample-1.sql",
  "tablesample-2.sql",
  "tablesample-3.sql",
  "tablesample-4.sql",
  "tablesample-5.sql",
  "tablesample-6.sql",
  "tablesample-7.sql",
  "tablesample-8.sql",
  "tablesample-9.sql",
  "tablesample-10.sql",
  "tablesample-11.sql",
  "tablesample-12.sql",
  "tablesample-13.sql",
  "tablesample-14.sql",
  "tablesample-15.sql",
  "tablesample-16.sql",
  "tablesample-17.sql",
  "tablesample-18.sql",
  "tablesample-19.sql",
  "tablesample-20.sql",
  "tablesample-21.sql",
  "tablesample-22.sql",
  "tablesample-23.sql",
  "tablesample-24.sql",
  "tablesample-25.sql",
  "tablesample-26.sql",
  "tablesample-27.sql",
  "tablesample-28.sql",
  "tablesample-29.sql",
  "tablesample-30.sql",
  "tablesample-31.sql",
  "tablesample-32.sql",
  "tablesample-33.sql",
  "tablesample-34.sql",
  "tablesample-35.sql",
  "tablesample-36.sql",
  "tablesample-37.sql",
  "tablesample-38.sql",
  "tablesample-39.sql",
  "tablesample-40.sql",
  "tablesample-41.sql",
  "tablesample-42.sql",
  "tablesample-43.sql",
  "tablesample-44.sql",
  "tablesample-45.sql",
  "tablesample-46.sql",
  "tablesample-47.sql",
  "tablesample-48.sql",
  "tablesample-49.sql"
]);
});
