ALTER TABLE public.table1 ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.table1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.sales
ADD COLUMN total_price NUMERIC GENERATED ALWAYS AS (quantity * unit_price) STORED;

ALTER TABLE public.comments
ADD COLUMN post_id INTEGER NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE;

ALTER TABLE public.devices
ADD COLUMN device_token UUID UNIQUE DEFAULT gen_random_uuid();

ALTER TABLE public.products
ADD COLUMN product_id BIGINT GENERATED BY DEFAULT AS IDENTITY (
    START WITH 5000
    INCREMENT BY 10
);

ALTER TABLE public.users
ADD COLUMN name TEXT COLLATE "fr_FR";

ALTER TABLE public.books
ADD COLUMN tags TEXT[] DEFAULT '{}';

CREATE TYPE mood AS ENUM ('happy', 'sad', 'neutral');

ALTER TABLE public.profiles
ADD COLUMN current_mood mood DEFAULT 'neutral';